In [12]:
import numpy as np

x = np.arange(30).reshape(-1,2)

In [13]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [20]:
x1, x2 = x[:, 0], x[:, 1]

In [46]:
grad

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [48]:
# gradient = hstack([x1,])
x2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [75]:
z= np.zeros(x)

TypeError: only integer scalar arrays can be converted to a scalar index

In [77]:
# grad = np.empty_like(x)
grad = np.zeros(x.shape)

grad[:,0] = x1
grad[:,1] = 2*(x2 - 1)
# return grad.squeeze()

In [78]:
grad

array([[ 0.,  0.],
       [ 2.,  4.],
       [ 4.,  8.],
       [ 6., 12.],
       [ 8., 16.],
       [10., 20.],
       [12., 24.],
       [14., 28.],
       [16., 32.],
       [18., 36.],
       [20., 40.],
       [22., 44.],
       [24., 48.],
       [26., 52.],
       [28., 56.]])

In [79]:
grad.squeeze()

array([[ 0.,  0.],
       [ 2.,  4.],
       [ 4.,  8.],
       [ 6., 12.],
       [ 8., 16.],
       [10., 20.],
       [12., 24.],
       [14., 28.],
       [16., 32.],
       [18., 36.],
       [20., 40.],
       [22., 44.],
       [24., 48.],
       [26., 52.],
       [28., 56.]])

In [85]:
a = np.arange(15)

In [86]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
(a.T).shape

(15,)

In [88]:
grad

array([[ 0.,  0.],
       [ 2.,  4.],
       [ 4.,  8.],
       [ 6., 12.],
       [ 8., 16.],
       [10., 20.],
       [12., 24.],
       [14., 28.],
       [16., 32.],
       [18., 36.],
       [20., 40.],
       [22., 44.],
       [24., 48.],
       [26., 52.],
       [28., 56.]])

In [89]:
grad.shape

(15, 2)

In [90]:
a.shape

(15,)

In [93]:
grad[:,1] = a

In [94]:
grad

array([[ 0.,  0.],
       [ 2.,  1.],
       [ 4.,  2.],
       [ 6.,  3.],
       [ 8.,  4.],
       [10.,  5.],
       [12.,  6.],
       [14.,  7.],
       [16.,  8.],
       [18.,  9.],
       [20., 10.],
       [22., 11.],
       [24., 12.],
       [26., 13.],
       [28., 14.]])

In [95]:
 test_set = np.zeros((20,2))

In [96]:
test_set

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [98]:
test_set[:, 1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [101]:
q = np.linspace(-1.2, 4.8, 20)

In [102]:
q

array([-1.2       , -0.88421053, -0.56842105, -0.25263158,  0.06315789,
        0.37894737,  0.69473684,  1.01052632,  1.32631579,  1.64210526,
        1.95789474,  2.27368421,  2.58947368,  2.90526316,  3.22105263,
        3.53684211,  3.85263158,  4.16842105,  4.48421053,  4.8       ])

In [103]:
test_set[:, 1] = q

In [104]:
test_set

array([[ 0.        , -1.2       ],
       [ 0.        , -0.88421053],
       [ 0.        , -0.56842105],
       [ 0.        , -0.25263158],
       [ 0.        ,  0.06315789],
       [ 0.        ,  0.37894737],
       [ 0.        ,  0.69473684],
       [ 0.        ,  1.01052632],
       [ 0.        ,  1.32631579],
       [ 0.        ,  1.64210526],
       [ 0.        ,  1.95789474],
       [ 0.        ,  2.27368421],
       [ 0.        ,  2.58947368],
       [ 0.        ,  2.90526316],
       [ 0.        ,  3.22105263],
       [ 0.        ,  3.53684211],
       [ 0.        ,  3.85263158],
       [ 0.        ,  4.16842105],
       [ 0.        ,  4.48421053],
       [ 0.        ,  4.8       ]])